Hi-Match/Hi-Match-BE

- src/main/java/kr/co/himatch/thanksyouplz/company/controller/CompanyController.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanyInfoDetailResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanyInfoRegisterRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanyInfoRegisterResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanyInfoTagRegisterDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanyInfoTagResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/dto/CompanySignupRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/company/entity/Company.java
- src/main/java/kr/co/himatch/thanksyouplz/company/entity/CompanyLog.java
- src/main/java/kr/co/himatch/thanksyouplz/company/entity/CompanyTag.java
- src/main/java/kr/co/himatch/thanksyouplz/company/entity/Tag.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/CompanyRepositoryCustom.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/CompanyRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/CompanyTagRepository.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/CompanyTagRepositoryCustom.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/CompanyTagRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/TagRepository.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/TagRepositoryCustom.java
- src/main/java/kr/co/himatch/thanksyouplz/company/repository/TagRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/company/service/CompanyService.java
- src/main/java/kr/co/himatch/thanksyouplz/company/service/CompanyServiceImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/company/service/TagService.java
- src/main/java/kr/co/himatch/thanksyouplz/company/service/TagServiceImpl.java
[merge/Dev] ✨feat: Company 기업 상세 조회 등록 및 tag API 구현
> [merge/Dev] ✨feat: Company 기업 상세 조회 등록 및 tag API 구현

- src/main/java/kr/co/himatch/thanksyouplz/application/controller/ApplicationContoller.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationMemberJobListRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationMemberJobListResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationMemberSearchPageRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationMemberSearchPageResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/repository/JobPostingRepositoryCustom.java
- src/main/java/kr/co/himatch/thanksyouplz/application/repository/JobPostingRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationService.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/auth/Constants.java
[Dev/merge] ✨ feat: Application 공고 검색 기능 main branch merge #3
> [Dev/merge] ✨ feat: Application 공고 검색 기능 main branch merge #3

- src/main/java/kr/co/himatch/thanksyouplz/application/entity/ApplicationSchool.java
- src/main/java/kr/co/himatch/thanksyouplz/resume/entity/ResumeSchool.java
- src/main/java/kr/co/himatch/thanksyouplz/resume/service/ResumeServiceImpl.java
[Dev/merge] ✨feat: 이력서 주석 첨부 및 ERD 수정
>  [Dev/merge] ✨feat: 이력서 주석 첨부 및 ERD 수정

- Dockerfile
[Dev/merge] ✨feat: docker 환경에서 파이썬 transformer 라이브러리 설치
> [Dev/merge] ✨feat: docker 환경에서 파이썬 transformer 라이브러리 설치

- Dockerfile
[Dev/merge] :sparkles:feat: 모델 다운로드 (선택 사항 - 컨테이너 이미지 크기 고려)
> [Dev/merge] :sparkles:feat: 모델 다운로드 (선택 사항 - 컨테이너 이미지 크기 고려)

- Dockerfile
[Dev/merge] ✨feat: docker 환경에서 파이썬 transformer 라이브러리 버전 명시
> [Dev/merge] ✨feat: docker 환경에서 파이썬 transformer 라이브러리 버전 명시

- Dockerfile
[Dev/Merge] ✨feat: docker 환경에서 파이썬 PyTorch 라이브러리 추가
> [Dev/Merge] ✨feat: docker 환경에서 파이썬 PyTorch 라이브러리 추가

- Dockerfile
[Dev/merge] ✨feat: docker 환경에서 파이썬 pytoch 저사양 라이브러리 변경
> [Dev/merge] ✨feat: docker 환경에서 파이썬 pytoch 저사양 라이브러리 변경

- Dockerfile
> [Dev/merge] 🐛 :fix: 철자 오류 수정

- Dockerfile
- src/main/java/kr/co/himatch/thanksyouplz/member/service/S3UploadService.java
[Dev/merge] :bug: fix: 메모리 부족으로 원복
> [Dev/merge] :bug: fix: 메모리 부족으로 원복

- build.gradle
[Dev/merge] 🔨 chore : 빌드 배포시 txt파일 추가하여 인성검사 API 오류 해결하기
> [Dev/merge] 🔨 chore : 빌드 배포시 txt파일 추가하여 인성검사 API 오류 해결하기

- build.gradle
- src/main/java/kr/co/himatch/thanksyouplz/code/util/FileUtil.java
[dev/merge] 🔨 chore : 빌드 배포시 suitability파일 추가 및 파일 불러오는 코드 변경
> [dev/merge] 🔨 chore : 빌드 배포시 suitability파일 추가 및 파일 불러오는 코드 변경

- src/main/java/kr/co/himatch/thanksyouplz/code/controller/CodeController.java
- src/main/java/kr/co/himatch/thanksyouplz/code/dto/CodeMemberResultRateDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/code/dto/CodeMemberResultResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/code/dto/CodeMemberResultSuccessResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/code/service/CodeService.java
- src/main/java/kr/co/himatch/thanksyouplz/code/service/CodeServiceImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/code/util/PersonalTypeConstants.java
- src/main/java/kr/co/himatch/thanksyouplz/member/entity/Member.java
- src/main/java/kr/co/himatch/thanksyouplz/member/entity/MemberLog.java
[dev/merge] ✨feat : AI 인성검사 분석 API 구현 완료
> [dev/merge] ✨feat : AI 인성검사 분석 API 구현 완료

- src/main/java/kr/co/himatch/thanksyouplz/application/controller/ApplicationContoller.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationMemberJobListResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/repository/JobPostingRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationService.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/auth/Constants.java
- src/main/java/kr/co/himatch/thanksyouplz/auth/jwt/JsonWebTokenCheckFilter.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/repository/BookMarkRepository.java
- src/main/java/kr/co/himatch/thanksyouplz/code/service/CodeServiceImpl.java
[dev/merge] 채용 공고의 비회원 회원 분기 및 회사 이미지A 등록 및 bookmark 표시 완료
> [dev/merge] 채용 공고의 비회원 회원 분기 및 회사 이미지A 등록 및 bookmark 표시 완료

- src/main/java/kr/co/himatch/thanksyouplz/application/controller/ApplicationContoller.java
- src/main/java/kr/co/himatch/thanksyouplz/application/repository/ApplicationRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
[dev/merge] ✨ applicationName 변경 /member 부분은 회사명으로, /company 부분은 지원자명으로 수정 완료
> [dev/merge] ✨ applicationName 변경 /member 부분은 회사명으로, /company 부분은 지원자명으로 수정 완료

- src/main/java/kr/co/himatch/thanksyouplz/bookmark/controller/BookMarkController.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/dto/BookMarkPageRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/repository/BookMarkRepositoryCustom.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/repository/BookMarkRepositoryImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/service/BookMarkService.java
- src/main/java/kr/co/himatch/thanksyouplz/bookmark/service/BookMarkServiceImpl.java
> [Dev/merge]♻️ :refactor: 북마크 페이지네이션 시, Requestbody 생성 후 keyword 추가하여 검색 페이지 페이지네이션 추가

- src/main/java/kr/co/himatch/thanksyouplz/auth/jwt/JsonWebTokenCheckFilter.java
[dev/merge] ✨feat: cookie null 상태 오류 해결 (cookie 없어도 접근 허용)
> [dev/merge] ✨feat: cookie null 상태 오류 해결 (cookie 없어도 접근 허용)

- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanySelectResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
[dev/merge] :sparkles: 공고 조회시 상세 내용 조회할 수 있도록 내용 추가
> [dev/merge] :sparkles: 공고 조회시 상세 내용 조회할 수 있도록 내용 추가

- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanyModifyRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanyRegisterRequestDTO.java
[dev/merge]:sparkles: 채용 공고 근무시간 타입을 HH:mm 타입으로 변경
> [dev/merge]:sparkles: 채용 공고 근무시간 타입을 HH:mm 타입으로 변경

- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanyModifyRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanyRegisterRequestDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanySelectResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/entity/JobPosting.java
[dev/merge] :sparkles: 채용 공고 근무시간 타입을 HH:mm LocalTime으로 변경
> [dev/merge] :sparkles: 채용 공고 근무시간 타입을 HH:mm LocalTime으로 변경

- src/main/java/kr/co/himatch/thanksyouplz/application/entity/JobPosting.java
[dev/merge] :sparkles: postingContent 사이즈 변경
> [dev/merge] :sparkles: postingContent 사이즈 변경

- src/main/java/kr/co/himatch/thanksyouplz/application/repository/JobPostingRepositoryImpl.java
[dev/merge] :sparkles: 채용 공고 조회 정렬을 최신 순으로 변경
> [dev/merge] :sparkles: 채용 공고 조회 정렬을 최신 순으로 변경

- src/main/java/kr/co/himatch/thanksyouplz/application/entity/JobPosting.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
- src/main/java/kr/co/himatch/thanksyouplz/auth/Constants.java
[dev/merge] :sparkles: 채용 공고 조기 마감 isfinished 수정
> [dev/merge] :sparkles: 채용 공고 조기 마감 isfinished 수정

- sql/table.sql
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
> [dev/merge] ✨ 이력서 상세 조회 오류 수정

- src/main/java/kr/co/himatch/thanksyouplz/application/dto/ApplicationCompanyApplyDetailResponseDTO.java
- src/main/java/kr/co/himatch/thanksyouplz/application/service/ApplicationServiceImpl.java
[dev/merge] :sparkles: 이력서 상세 조회 부족한 데이터 추가 pf, status, result
> [dev/merge] :sparkles: 이력서 상세 조회 부족한 데이터 추가 pf, status, result
